In [1]:
#basic Dataframe understanding

In [2]:
import pandas as pd

In [3]:
data = {
    'name':['ram','ravi','ak','vj','av','rt'],
    'age':[26,37,28,19,12,23],
    'salary':[1000,3000,4000,5000,2000,3000]
}

df = pd.DataFrame(data)

print(df)
print(type(df))

   name  age  salary
0   ram   26    1000
1  ravi   37    3000
2    ak   28    4000
3    vj   19    5000
4    av   12    2000
5    rt   23    3000
<class 'pandas.DataFrame'>

In [4]:
df.head(2) # top rows

   name  age  salary
0   ram   26    1000
1  ravi   37    3000

In [7]:
df.tail(2) #last rows

  name  age  salary
4   av   12    2000
5   rt   23    3000

In [8]:
df.shape # return tuple containing the shape of DataFrame - row & column

(6, 3)

In [9]:
df.columns #list of column name in df

Index(['name', 'age', 'salary'], dtype='str')

In [10]:
df.rename(columns={'Salary':'Monthly_salary'}) # rename abhi df mi change nhi hua hai
print(df)

   name  age  salary
0   ram   26    1000
1  ravi   37    3000
2    ak   28    4000
3    vj   19    5000
4    av   12    2000
5    rt   23    3000

In [11]:
df.rename(columns={'salary':'Monthly_salary'}, inplace=True)

print(df) # rename column name

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
4    av   12            2000
5    rt   23            3000

In [12]:
df.info() # info method print information about the data frame

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            6 non-null      str
 1   age             6 non-null      int64
 2   Monthly_salary  6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [13]:
df.describe() # describe method generates descriptive statics of data frame

             age  Monthly_salary
count   6.000000        6.000000
mean   24.166667     3000.000000
std     8.471521     1414.213562
min    12.000000     1000.000000
25%    20.000000     2250.000000
50%    24.500000     3000.000000
75%    27.500000     3750.000000
max    37.000000     5000.000000

In [14]:
df.to_csv('pn_data.csv')  # upload data in csv file

In [15]:
df.to_csv('data.csv', index=False)  #data upload withod index value