In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('data.csv') # load file 
print(df) # all data show
df[['name']] # only single column

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
4    av   12            2000
5    rt   23            3000

   name
0   ram
1  ravi
2    ak
3    vj
4    av
5    rt

In [3]:
df[['name','Monthly_salary']]
# select multiple column

   name  Monthly_salary
0   ram            1000
1  ravi            3000
2    ak            4000
3    vj            5000
4    av            2000
5    rt            3000

In [4]:
# select single row // loc labe based index // loc row ko filters select karta hai
df.loc[df.name=='ravi']

   name  age  Monthly_salary
1  ravi   37            3000

In [6]:
# selct multiple row based index
df.loc[(df.name=='ram')& (df.Monthly_salary>=3000)]  # mupltiple filter

Empty DataFrame
Columns: [name, age, Monthly_salary]
Index: []

In [4]:
df.loc[0:2] # als0 2 include

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000

In [5]:
#select row//iloc- index value based
#df.iloc[0]
df.iloc[0:5:2] # [start:stop:step]

  name  age  Monthly_salary
0  ram   26            1000
2   ak   28            4000
4   av   12            2000

In [14]:
df.loc[0:2] # [0 se 2 ko bhi include kr raha hai]
df.iloc[0:2] # [start:stop:step] ye nhi krta 2 ko

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000

In [15]:
#filter dataframe- filtering by column values
df

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
4    av   12            2000
5    rt   23            3000

In [16]:
df['age']>=18  # data show in true /flase

0     True
1     True
2     True
3     True
4    False
5     True
Name: age, dtype: bool

In [17]:
df[df['age']>=18]  # only see 18 equale and 18+ show in table

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
5    rt   23            3000

In [6]:
df_age_filter = df[df['age']>=18] # filter and data store in new variable
df_age_filter

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
5    rt   23            3000

In [14]:
df[(df['age']>=18) &(df['Monthly_salary']>=3000)]  #cremove under 18 and salary below 3000

   name  age  Monthly_salary
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
5    rt   23            3000

In [15]:
df.where(df['age']>=20)  # where  function  replce a data frame basedon a conduition

   name   age  Monthly_salary
0   ram  26.0          1000.0
1  ravi  37.0          3000.0
2    ak  28.0          4000.0
3   NaN   NaN             NaN
4   NaN   NaN             NaN
5    rt  23.0          3000.0

In [20]:
df.where(df['age'] >=18,other = 'not eligible')

           name           age Monthly_salary
0           ram            26           1000
1          ravi            37           3000
2            ak            28           4000
3            vj            19           5000
4  not eligible  not eligible   not eligible
5            rt            23           3000

In [21]:
#rows and columns - operation(add,upadate,delect)

In [21]:
#create a new column
df['college'] =['rjit' ,'itm','mits','abc','vck','itm']
df

   name  age  Monthly_salary        DOJ2 college
0   ram   26            1000  2024-01-01    rjit
1  ravi   37            3000  2024-01-15     itm
2    ak   28            4000  2024-03-28    mits
3    vj   19            5000  2024-03-03     abc
4    av   12            2000  2024-04-03     vck
5    rt   23            3000  2024-05-01     itm

In [26]:
#add new column using exisiting coulmn/s
df['bonus'] = df['Monthly_salary'] * 0.20
df

   name  age  Monthly_salary college   bonus
0   ram   26            1000    rjit   200.0
1  ravi   37            3000     itm   600.0
2    ak   28            4000    mits   800.0
3    vj   19            5000     abc  1000.0
4    av   12            2000     vck   400.0
5    rt   23            3000     itm   600.0

In [28]:
#add new row - at the end of dataframe
df.loc[len(df)] =['viki',23,2000,'mpct',1000]
df

   name  age  Monthly_salary college   bonus
0   ram   26            1000    rjit   200.0
1  ravi   37            3000     itm   600.0
2    ak   28            4000    mits   800.0
3    vj   19            5000     abc  1000.0
4    av   12            2000     vck   400.0
5    rt   23            3000     itm   600.0
6  viki   23            2000    mpct  1000.0

In [30]:
#update value in dataframe using column -value
df.loc[df.name=='ram','salary'] =110000
df

   name  age  Monthly_salary college   bonus    salary
0   ram   26            1000    rjit   200.0  110000.0
1  ravi   37            3000     itm   600.0       NaN
2    ak   28            4000    mits   800.0       NaN
3    vj   19            5000     abc  1000.0       NaN
4    av   12            2000     vck   400.0       NaN
5    rt   23            3000     itm   600.0       NaN
6  viki   23            2000    mpct  1000.0       NaN

In [31]:
#delete value - rows and columns

In [35]:
#delete row (using column -value filter

df=df.drop(df[df.name == 'viki'].index) #delete row ,axis =0
df

   name  age  Monthly_salary college   bonus    salary
0   ram   26            1000    rjit   200.0  110000.0
1  ravi   37            3000     itm   600.0       NaN
2    ak   28            4000    mits   800.0       NaN
3    vj   19            5000     abc  1000.0       NaN
4    av   12            2000     vck   400.0       NaN
5    rt   23            3000     itm   600.0       NaN

In [36]:
#delete  row using index -name filter 
df.drop(1,axis=0)

  name  age  Monthly_salary college   bonus    salary
0  ram   26            1000    rjit   200.0  110000.0
2   ak   28            4000    mits   800.0       NaN
3   vj   19            5000     abc  1000.0       NaN
4   av   12            2000     vck   400.0       NaN
5   rt   23            3000     itm   600.0       NaN

In [59]:
df.drop('bonus', axis=1, inplace=True)#delete one column
df
#df.drop(['bonus' ,'team'],axis=1,inplace= True) # delete multiple column

KeyError: "['bonus'] not found in axis"

In [56]:
#df.rename(columns = {'salary':'Monthly_salary'},inplace=True) # rename column name
df.rename(columns={'Monthly_salary':'salary'}, inplace=True )
df = df.loc[:, ~df.columns.duplicated()]
df

   name  age  salary college
0   ram   26    1000    rjit
1  ravi   37    3000     itm
2    ak   28    4000    mits
3    vj   19    5000     abc
4    av   12    2000     vck
5    rt   23    3000     itm

In [57]:
#sort value - order value in dataframe by asc or desc order
df.sort_values('salary') #ascending order ,by default
df

   name  age  salary college
0   ram   26    1000    rjit
1  ravi   37    3000     itm
2    ak   28    4000    mits
3    vj   19    5000     abc
4    av   12    2000     vck
5    rt   23    3000     itm

In [58]:
#sort value - order value in dataframe by asc or desc order
df.sort_values('salary',ascending =False) #ascending order ,by default
df

   name  age  salary college
0   ram   26    1000    rjit
1  ravi   37    3000     itm
2    ak   28    4000    mits
3    vj   19    5000     abc
4    av   12    2000     vck
5    rt   23    3000     itm

In [19]:
#working with date value
df

   name  age  Monthly_salary
0   ram   26            1000
1  ravi   37            3000
2    ak   28            4000
3    vj   19            5000
4    av   12            2000
5    rt   23            3000

In [25]:
# create a date column - date of joining
df['DOJ2'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03','2024-04-03','2024-05-01']
df

   name  age  Monthly_salary        DOJ2 college
0   ram   26            1000  2024-01-01    rjit
1  ravi   37            3000  2024-01-15     itm
2    ak   28            4000  2024-03-28    mits
3    vj   19            5000  2024-03-03     abc
4    av   12            2000  2024-04-03     vck
5    rt   23            3000  2024-05-01     itm

In [26]:
df['DOJ2'].dtype #

In [27]:
df['DOJ2'] = pd.to_datetime(df['DOJ2'])  #change to date -time type

In [28]:
df['DOJ2'].dtype #date-time type

dtype('<M8[us]')

In [29]:
df1 =df

In [30]:
#create a new column with icorrent date format
# creating a new column with incorrect date format
df1['DOJ23'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025','03-03-2025','03-03-2025']
df1

   name  age  Monthly_salary       DOJ2 college       DOJ23
0   ram   26            1000 2024-01-01    rjit  01-01-2025
1  ravi   37            3000 2024-01-15     itm  15-01-2025
2    ak   28            4000 2024-03-28    mits  28-03-2025
3    vj   19            5000 2024-03-03     abc  03-03-2025
4    av   12            2000 2024-04-03     vck  03-03-2025
5    rt   23            3000 2024-05-01     itm  03-03-2025

In [33]:
df['DOJ23'].dtype #date-time type

In [38]:
df1['DOJ23'] = pd.to_datetime(df1['DOJ23'], format='%d/%m/%y') #change to date-time type using date
df

ValueError: time data "01-01-2025" doesn't match format "%d/%m/%y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [39]:
#extract year,month ,week,day
df['DOJ2'].dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
5    2024
Name: DOJ2, dtype: int32

In [40]:
df['DOJ2'].dt.month

0    1
1    1
2    3
3    3
4    4
5    5
Name: DOJ2, dtype: int32

In [41]:
df['DOJ2'].dt.day

0     1
1    15
2    28
3     3
4     3
5     1
Name: DOJ2, dtype: int32

In [42]:
df['DOJ2'].dt.day_name()

0       Monday
1       Monday
2     Thursday
3       Sunday
4    Wednesday
5    Wednesday
Name: DOJ2, dtype: str

In [44]:
#create new column month exratct function from doj2
df['month'] = df['DOJ2'].dt.month
df

   name  age  Monthly_salary       DOJ2 college       DOJ23  month
0   ram   26            1000 2024-01-01    rjit  01-01-2025      1
1  ravi   37            3000 2024-01-15     itm  15-01-2025      1
2    ak   28            4000 2024-03-28    mits  28-03-2025      3
3    vj   19            5000 2024-03-03     abc  03-03-2025      3
4    av   12            2000 2024-04-03     vck  03-03-2025      4
5    rt   23            3000 2024-05-01     itm  03-03-2025      5

In [49]:
df['DOJ2'] + pd.Timedelta(days=90) # add 90 days to DOJ2 column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2024-07-02
5   2024-07-30
Name: DOJ2, dtype: datetime64[us]

In [50]:
#handling missing value 
df.isnull() # detect missing value

    name    age  Monthly_salary   DOJ2  college  DOJ23  month
0  False  False           False  False    False  False  False
1  False  False           False  False    False  False  False
2  False  False           False  False    False  False  False
3  False  False           False  False    False  False  False
4  False  False           False  False    False  False  False
5  False  False           False  False    False  False  False

In [56]:
import numpy as np #to create null value
df.loc[df.name=='rt','Monthly_salary'] = np.nan # adding a null value
df

   name  age  Monthly_salary       DOJ2 college       DOJ23  month  salary
0   ram   26          1000.0 2024-01-01    rjit  01-01-2025      1     NaN
1  ravi   37          3000.0 2024-01-15     itm  15-01-2025      1     NaN
2    ak   28          4000.0 2024-03-28    mits  28-03-2025      3     NaN
3    vj   19          5000.0 2024-03-03     abc  03-03-2025      3     NaN
4    av   12          2000.0 2024-04-03     vck  03-03-2025      4     NaN
5    rt   23             NaN 2024-05-01     itm  03-03-2025      5     NaN

In [57]:
df.isnull() # detect missing value

    name    age  Monthly_salary   DOJ2  college  DOJ23  month  salary
0  False  False           False  False    False  False  False    True
1  False  False           False  False    False  False  False    True
2  False  False           False  False    False  False  False    True
3  False  False           False  False    False  False  False    True
4  False  False           False  False    False  False  False    True
5  False  False            True  False    False  False  False    True

In [60]:
df.isnull().sum()  # calculate count null values

name              0
age               0
Monthly_salary    1
DOJ2              0
college           0
DOJ23             0
month             0
salary            6
dtype: int64

In [61]:
df.fillna(0) # fill null value with 0

   name  age  Monthly_salary       DOJ2 college       DOJ23  month  salary
0   ram   26          1000.0 2024-01-01    rjit  01-01-2025      1     0.0
1  ravi   37          3000.0 2024-01-15     itm  15-01-2025      1     0.0
2    ak   28          4000.0 2024-03-28    mits  28-03-2025      3     0.0
3    vj   19          5000.0 2024-03-03     abc  03-03-2025      3     0.0
4    av   12          2000.0 2024-04-03     vck  03-03-2025      4     0.0
5    rt   23             0.0 2024-05-01     itm  03-03-2025      5     0.0

In [64]:
df.loc[df.name=='ram', 'salary'] = 3000 # single
df

# df.loc[df.name.isin](['ram','ravi']),'salary'] = 2000# multiple

   name  age  Monthly_salary       DOJ2 college       DOJ23  month  salary
0   ram   26          1000.0 2024-01-01    rjit  01-01-2025      1  3000.0
1  ravi   37          3000.0 2024-01-15     itm  15-01-2025      1     NaN
2    ak   28          4000.0 2024-03-28    mits  28-03-2025      3     NaN
3    vj   19          5000.0 2024-03-03     abc  03-03-2025      3     NaN
4    av   12          2000.0 2024-04-03     vck  03-03-2025      4     NaN
5    rt   23             NaN 2024-05-01     itm  03-03-2025      5     NaN

In [68]:
df.loc[df.name.isin(['ram','ravi']),'Monthly_salary'] = 5000  # multiple
df

   name  age  Monthly_salary       DOJ2 college       DOJ23  month  salary
0   ram   26          5000.0 2024-01-01    rjit  01-01-2025      1  2000.0
1  ravi   37          5000.0 2024-01-15     itm  15-01-2025      1  2000.0
2    ak   28          4000.0 2024-03-28    mits  28-03-2025      3     NaN
3    vj   19          5000.0 2024-03-03     abc  03-03-2025      3     NaN
4    av   12          2000.0 2024-04-03     vck  03-03-2025      4     NaN
5    rt   23             NaN 2024-05-01     itm  03-03-2025      5     NaN