In [1]:
# 🔷 1. GroupBy kya hota hai?

# 👉 groupby() ka matlab:

# “Same category wale data ko group karo”

# Example:

# Department wise salary
# City wise sales
# Gender wise marks

# df.groupby('column_name')

In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Ram', 'Ravi', 'Amit', 'Ram', 'Ravi'],
    'Dept': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Salary': [30000, 25000, 40000, 32000, 28000]
}

df = pd.DataFrame(data)

In [3]:
print(df)

   Name Dept  Salary
0   Ram   IT   30000
1  Ravi   HR   25000
2  Amit   IT   40000
3   Ram   HR   32000
4  Ravi   IT   28000

In [4]:
# 2. Aggregation kya hota hai?
# 👉 Aggregation ka matlab:

# “Grouped data par calculation karna”

# Common functions:

# sum()
# mean()
# min()
# max()
# count()

In [5]:
df['Dept'].value_counts() # frequency values in month column

Dept
IT    3
HR    2
Name: count, dtype: int64

In [6]:
df[df['Dept']=='IT'].value_counts() #frequncy

Name  Dept  Salary
Ram   IT    30000     1
Amit  IT    40000     1
Ravi  IT    28000     1
Name: count, dtype: int64

In [7]:
#depatrtment wise total salary[]
df.groupby('Dept')['Salary'].sum()

Dept
HR    57000
IT    98000
Name: Salary, dtype: int64

In [8]:
#department wise total avg salary
df.groupby('Dept')['Salary'].mean()

Dept
HR    28500.000000
IT    32666.666667
Name: Salary, dtype: float64

In [9]:
#count of employees per department
df.groupby('Dept')['Name'].count()

Dept
HR    2
IT    3
Name: Name, dtype: int64

In [10]:
#multiple aggregations(most important)

df.groupby('Dept')['Salary'].agg(['sum','mean','min','max'])

        sum          mean    min    max
Dept
HR    57000  28500.000000  25000  32000
IT    98000  32666.666667  28000  40000

In [11]:
#multiple column group by  dept +name combination wise result
df.groupby(['Dept','Name'])['Salary'].sum()

Dept  Name
HR    Ram     32000
      Ravi    25000
IT    Amit    40000
      Ram     30000
      Ravi    28000
Name: Salary, dtype: int64

In [12]:
#name aggregation (advanced)
df.groupby('Dept').agg(
    total_salary=('Salary','sum'),
    avg_salary =('Salary','mean'),
    count_emp=('Name','count') )

      total_salary    avg_salary  count_emp
Dept
HR           57000  28500.000000          2
IT           98000  32666.666667          3

In [13]:
df.to_csv('data2.csv')

In [14]:
# ⚡ 8. Simple Trick to Remember

# 👉 GroupBy = “Category banana”
# 👉 Aggregation = “Calculation karna”


# Concept	Meaning
# groupby()	Data ko groups me divide karta hai
# aggregation	grouped data par calculation karta hai
# agg()	multiple functions ek saath

# Pandas me GroupBy + Aggregation = Data Analysis ka backbone hai

In [15]:
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Keyboard', 'Laptop'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South', 'North'],
    'Sales': [50000, 500, 1500, 55000, 600, 1400, 60000],
    'Profit': [8000, 100, 300, 9000, 120, 280, 10000]
}

df = pd.DataFrame(data)
df

    Product Region  Sales  Profit
0    Laptop  North  50000    8000
1     Mouse  South    500     100
2  Keyboard  North   1500     300
3    Laptop  South  55000    9000
4     Mouse  North    600     120
5  Keyboard  South   1400     280
6    Laptop  North  60000   10000

In [16]:
#product wise sales
df.groupby('Product')['Sales'].sum()

Product
Keyboard      2900
Laptop      165000
Mouse         1100
Name: Sales, dtype: int64

In [17]:
#product wise average profit
df.groupby('Product')['Profit'].mean()

Product
Keyboard     290.0
Laptop      9000.0
Mouse        110.0
Name: Profit, dtype: float64

In [18]:
#region wise tatal sales
df.groupby('Region')['Sales'].sum()

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [19]:
# region wise profit
df.groupby('Region')['Profit'].sum()

Region
North    18420
South     9380
Name: Profit, dtype: int64

In [20]:
#best selling product
df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

Product
Laptop      165000
Keyboard      2900
Mouse         1100
Name: Sales, dtype: int64

In [26]:
#full bussiness report (most imp)
report = df.groupby('Product').agg(
    total_sales=('Sales', 'sum'),
    avg_sales=('Sales', 'mean'),
    total_profit=('Profit', 'sum'),
    avg_profit=('Profit', 'mean')
)

report

          total_sales  avg_sales  total_profit  avg_profit
Product
Keyboard         2900     1450.0           580       290.0
Laptop         165000    55000.0         27000      9000.0
Mouse            1100      550.0           220       110.0

In [27]:
#top performaing region
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [34]:
df.groupby('Product')['Sales'].sum().sort_values(ascending=True)

Product
Mouse         1100
Keyboard      2900
Laptop      165000
Name: Sales, dtype: int64