In [1]:
import pandas as pd

In [2]:
# 1. Concatenate (DataFrames ko jodna)

# 👉 concat() ka use hota hai:

# Multiple DataFrames ko stack (upar-neeche ya side-by-side) jodne ke liye
# pd.concat([df1, df2])

In [3]:
df1 = pd.DataFrame({
    'name':['ram','ravi'],
    'age':[25,30]
})
df2= pd.DataFrame({
    'name':['amit','sita'],
    'age':[28,22]
})
#result=pd.concat([df1,df2],axis =0) # c
result=pd.concat([df1,df2],axis=0) # concatenate:horizontal/column/level sql joins

In [15]:
df1 = pd.DataFrame({
    'empid': [1,2,3],
    'name': ['ram','ravi','amit']
})
df2 =pd.DataFrame({
    'empid':[1,2,4],
    'salary':[30000,40000,50000]
})

In [16]:
pd.merge(df1,df2,on='empid') #inner join (defaoult ) sirf matching data

   empid  name  salary
0      1   ram   30000
1      2  ravi   40000

In [17]:
#left join tablle ka sab data + matching right
pd.merge(df1,df2,on='empid',how='left') # left join

   empid  name   salary
0      1   ram  30000.0
1      2  ravi  40000.0
2      3  amit      NaN

In [18]:
#right join table ka sab data + matching left

pd.merge(df1,df2,on='empid',how='right') # right join

   empid  name  salary
0      1   ram   30000
1      2  ravi   40000
2      4   NaN   50000

In [21]:
# outer join sab data show karega table ka 
pd.merge(df1,df2,on ='empid',how='outer')

   empid  name   salary
0      1   ram  30000.0
1      2  ravi  40000.0
2      3  amit      NaN
3      4   NaN  50000.0

In [22]:

# Join Type	Result
# Inner	Only matching
# Left	Left + matching right
# Right	Right + matching
# Outer	All data

In [26]:
# Dono DataFrame ko empid column ke basis par inner join se merge kiya


pd.merge(df1,df2,how='inner',left_on='empid',right_on='empid')

   empid  name  salary
0      1   ram   30000
1      2  ravi   40000

In [ ]:
s