In [1]:
import pandas as pd
data = pd.Series([10,20,30],index = [ 1 ,2 ,3])
print(data)

1    10
2    20
3    30
dtype: int64

In [2]:
df = pd.DataFrame({
'a':['ram','wedw'],
'b':['moahn','edwd'],
 'c':['syam','wfe']
})
print(df)

      a      b     c
0   ram  moahn  syam
1  wedw   edwd   wfe

In [5]:
df.head(1)

     a      b     c
0  ram  moahn  syam

In [6]:
df.tail()

      a      b     c
0   ram  moahn  syam
1  wedw   edwd   wfe

In [14]:
df.rename(columns={'c':'d'}, inplace = True)
print(df)

      a      b     d
0   ram  moahn  syam
1  wedw   edwd   wfe

In [15]:
df

      a      b     d
0   ram  moahn  syam
1  wedw   edwd   wfe

In [16]:
df.info

<bound method DataFrame.info of       a      b     d
0   ram  moahn  syam
1  wedw   edwd   wfe>

In [18]:
df['e'] = [10,20]
df

      a      b     d   e
0   ram  moahn  syam  10
1  wedw   edwd   wfe  20

In [20]:
df['e']>=18

0    False
1     True
Name: e, dtype: bool

In [21]:
df[df['e']>=18]

      a     b    d   e
1  wedw  edwd  wfe  20

In [22]:
df.where(df['e']>=18)

      a     b    d     e
0   NaN   NaN  NaN   NaN
1  wedw  edwd  wfe  20.0

In [24]:
df.loc[len(df)]=['mohn','ssd','scs',28]
df

      a      b     d   e
0   ram  moahn  syam  10
1  wedw   edwd   wfe  20
2  mohn    ssd   scs  28
3  mohn    ssd   scs  28

In [25]:
df.drop(3,axis=0)

      a      b     d   e
0   ram  moahn  syam  10
1  wedw   edwd   wfe  20
2  mohn    ssd   scs  28

In [1]:
import pandas as pd

In [8]:
data = {
    'name': ['shaym','mohan','lovekush'],
    'age' : [12,25,20],
    'salary': [120000,29000,32000]
}

In [10]:
df=pd.DataFrame(data)

In [11]:
df

       name  age  salary
0     shaym   12  120000
1     mohan   25   29000
2  lovekush   20   32000

In [16]:
df.rename(columns={'salary':'monthly_salary'},inplace=True)

In [17]:
df

       name  age  monthly_salary
0     shaym   12          120000
1     mohan   25           29000
2  lovekush   20           32000

In [19]:
df.describe()

             age  monthly_salary
count   3.000000        3.000000
mean   19.000000    60333.333333
std     6.557439    51694.616096
min    12.000000    29000.000000
25%    16.000000    30500.000000
50%    20.000000    32000.000000
75%    22.500000    76000.000000
max    25.000000   120000.000000